quarkus:
  http:
    port: 9999
  datasource:
    url: jdbc:postgresql://192.168.33.4:5432/postgres
    driver: org.postgresql.Driver
    username: postgres
    password: postgres
  flyway:
    migrate-at-start: true

